<div style="background:#EAF0EE;border:1px solid #CCCCCC;margin-bottom:10px;padding:11px 0 0 10px;">
    <h4>
        <img src="http://www.magepsycho.com/_logo.png" style="height: 90px; padding-left: 20px;"/><br>
        <div style="padding-left: 30px;">
            <p>
                <strong style="color:#EA7601;">
                    <?php echo __('Easy Template Path Hints v') ?><?php echo $this->getModuleVersion() ?>
                    <?php echo __(' by') ?>
                </strong>
                <a target="_blank" href="http://www.magepsycho.com">
                    <strong>MagePsycho</strong>
                </a>
            </p>
            <p>
                <?php echo __('Need help? See our ') ?>
                <a href="http://www.blog.magepsycho.com/" target="_blank">
                    <?php echo __('Blog') ?>
                </a>
                <?php echo __(' or contact us via') ?>
                <a href="http://www.magepsycho.com/contacts/" target="_blank">
                    <?php echo __('Website') ?>
                </a>
                <?php echo __(' Got feedback? ') ?>
                <a href="mailto:magepsycho@gmail.com?Subject=M2 Easy Template Path Hints Version <?php echo $this->getModuleVersion()?> for <?php echo $this->getMageVersion() ?>">
                    <?php echo __('Email us') ?>
                </a>
            </p>

            <p style="padding-bottom: 10px;"><?php echo __('You can find more extensions in our ') ?><a href="http://www.magepsycho.com/extensions/magento-2.html" target="_blank"><?php echo __('Store') ?></a></p>

            <h3><a style="padding-top: 5px;padding-bottom:5px;padding-left: 30px;padding-right: 30px;background-color:#EB5202 ;color:white;font-weight: bold" href="http://www.magepsycho.com/contacts/" target="_blank"><?php echo __('Need Support? Contact us') ?></a></h3>
        </div>
    </h4>
</div>